{{- if .Values.configSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garagehq.configSecretName" . }}
  namespace: {{ include "chart-library.namespace" . | quote }}
  labels:
    {{- include "chart-library.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.configSecret.key }}: |
    metadata_dir = "{{ .Values.garage.metadataDir }}"
    data_dir = "{{ .Values.garage.dataDir }}"
    db_engine = "{{ .Values.garage.dbEngine }}"
    block_size = "{{ .Values.garage.blockSize }}"
    metadata_auto_snapshot_interval = "{{ .Values.garage.metadataAutoSnapshotInterval }}"

    replication_factor = {{ .Values.garage.replicationFactor }}
    consistency_mode = "{{ .Values.garage.consistencyMode }}"
    compression_level = {{ .Values.garage.compressionLevel }}

    rpc_bind_addr = "{{ .Values.garage.rpc.bindAddr }}"
    {{- if .Values.garage.rpc.publicAddr }}
    rpc_public_addr = "{{ .Values.garage.rpc.publicAddr }}"
    {{- end }}
    rpc_secret = "{{ .Values.garage.rpc.secret }}"

    bootstrap_peers = [
    {{- range $index, $peer := .Values.garage.bootstrapPeers }}
    {{- if $index}}, {{ end }}{{ $peer | quote }}
    {{- end }}
    ]

    {{- if .Values.garage.additionalTopLevelConfig }}
    {{ .Values.garage.additionalTopLevelConfig | nindent 4 }}
    {{- end }}

    {{- if .Values.garage.kubernetesDiscovery.enabled }}
    [kubernetes_discovery]
    namespace = "{{ .Release.Namespace }}"
    service_name = "{{ include "chart-library.fullname" . }}"
    skip_crd = {{ .Values.garage.kubernetesDiscovery.skipCrd }}
    {{- end }}

    [s3_api]
    s3_region = "{{ .Values.garage.s3Api.region }}"
    api_bind_addr = "{{ .Values.garage.s3Api.bindAddr }}"
    {{- if .Values.garage.s3Api.rootDomain }}
    root_domain = "{{ .Values.garage.s3Api.rootDomain }}"
    {{- end }}

    {{- if .Values.garage.s3Web.enabled }}
    [s3_web]
    bind_addr = "{{ .Values.garage.s3Web.bindAddr }}"
    {{- if .Values.garage.s3Web.rootDomain }}
    root_domain = "{{ .Values.garage.s3Web.rootDomain }}"
    {{- end }}
    index = "{{ .Values.garage.s3Web.index }}"
    {{- end }}

    [admin]
    api_bind_addr = "{{ .Values.garage.admin.bindAddr }}"
{{- end }}
