# workload
statefulset:
  enabled: true
  replicaCount: 1
  image:
    repository: quay.io/keycloak/keycloak
    tag: 26.3.2-1
  # settings - see https://www.keycloak.org/server/all-config
  args: [
    "start"
  ]
  extraEnv:
    # hostname
    - name: KC_HOSTNAME
      value: "https://keycloak.local"
    - name: KC_HOSTNAME_ADMIN
      value: "https://keycloak-admin.local"
    - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
      value: "true"
    # initial user
    - name: KC_BOOTSTRAP_ADMIN_USERNAME
      value: admin
    - name: KC_BOOTSTRAP_ADMIN_PASSWORD
      value: admin
    # db
    - name: KC_DB
      value: postgres
    - name: KC_DB_URL
      value: "<DBURL>"
    - name: KC_DB_USERNAME
      value: "<DBUSERNAME>"
    - name: KC_DB_PASSWORD
      value: "<DBPASSWORD>"
  # resources
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: keycloak.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

adminIngress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: keycloak-admin.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
